name: Keys4Change.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75965
title: Keys4Change
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff5900'
    - '#af0d01'
    - '#ffad00'
    - '#ffffff'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
