layout_spectrum: 1
color:
  saturation: 1
  brandStrength: 0.903455
  lightness: 0.7311828
  rhythmicContrast: 0.8351254
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.7903226
name: Keys4Change.com
